# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-XML-Simple
version:      0.08
version_from: lib/Test/XML/Simple.pm
installdirs:  site
requires:
    Test::Builder:                 0
    Test::More:                    0
    Test::Tester:                  0
    XML::LibXML:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.28
