--- #YAML:1.0
name:               Test-XML-Simple
version:            1.00
abstract:           easy testing for XML
author:
    - Joe McMahon <mcmahon@cpan.org>
license:            artistic
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::Builder:        0
    Test::Builder::Tester:  0
    Test::LongString:     0
    Test::More:           0
    XML::LibXML:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
